# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c20a4fffd47a8b60db689f890e1282c23979632c02c3add67c725af3ba6b8bf31fd978334c885720587cfe97d1822b8c6c2c0229a26d0890270a160dd2ad8bf

test:
  secret_key_base: e4a6070982e22d1f637648ef8e9ba628610c5f3203d1d9ba3d819f3980e356e6babf7c6c2aac00b659cdcc341f95a8c4196aa9c01c6beb021d962c418fd23c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
